#!/bin/sh

cat $@ \
    | tr -d '\r' \
    | sed -r 's/#.*//;/^\s*$/d' \
    | sed -r '
      1i# Init\ntag @e remove rm_cursor\n
      /^#/!s/\s*([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s*/# Region \1\nsummon armor_stand \4 150 \5 {CustomName:"\\"RegionMarker\\"",Marker:true,Invisible:true,CustomNameVisible:false,NoGravity:true,Invulnerable:true,Tags:["rm_cursor"]}\nscoreboard players set @e[tag=rm_cursor] region \1\nscoreboard players set @e[tag=rm_cursor] region_e1 \2\nscoreboard players set @e[tag=rm_cursor] region_e2 \3\nscoreboard players set @e[tag=rm_cursor] region_x \4\nscoreboard players set @e[tag=rm_cursor] region_z \5\ntag @e remove rm_cursor\n/'

exit

